kind: pipeline
name: default

steps:
- name: Configure Vault
  image: vault:0.11.4
  commands:
    - vault secrets disable secret
    - vault secrets enable -path=secret -version=1 kv
    - vault secrets enable totp
  environment:
    VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    VAULT_ADDR: http://vault:8200
  when:
    event:
      - pull_request

- name: Run rspec
  image: ruby:2.6.0
  environment:
    DATABASE_HOST: database
    EVENT_API_RABBITMQ_HOST: rabbitmq
    BARONG_VAULT_ADDR: http://vault:8200
    RAILS_ENV: test
    RAILS_MASTER_KEY:
      from_secret: rails_master_key
  commands:
    - bundle
    - ./bin/init_config
    - rake db:create db:migrate
    - rspec
  when:
    event:
      - pull_request

- name: Bump and tag
  image: ruby:2.6.0
  environment:
    DATABASE_HOST: database
    EVENT_API_RABBITMQ_HOST: rabbitmq
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    GITHUB_API_KEY:
      from_secret: kite_bot_key
    RAILS_MASTER_KEY:
      from_secret: rails_master_key
  commands:
    - gem install bump
    - git config --global user.name "  Kite Bot"
    - git config --global user.email "kite-bot@heliostech.fr"
    - git remote add authenticated-origin https://kite-bot:$GITHUB_API_KEY@github.com/${DRONE_REPO}
    - git fetch authenticated-origin
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - apt-get update && apt-get install -y nodejs
    - export V=$(cat VERSION)
    - bin/gendocs
    - git add .
    - bump patch --commit-message 'Bump [ci skip]'
    - git tag $(cat VERSION)
    - git push authenticated-origin ${DRONE_BRANCH}
    - git push --tags authenticated-origin
    - git describe --tags $(git rev-list --tags --max-count=1) > .tags
  when:
    event:
      - push
    branch:
      - master

- name: Docker build and push
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rubykube/barong
  when:
    event:
      - push
    branch:
      - master

- name: Redeploy
  image: rubykube/microkube:0.3.0
  environment:
      WEBHOOK_JWT_SECRET:
        from_secret: webhook_secret
      WEBHOOK_URL:
        from_secret: webhook_url
  commands:
    - export latest_image=rubykube/barong:$(cat .tags)
    - cd /home/app
    - bundle exec rake payload:send[barong,$latest_image,$WEBHOOK_URL]
  when:
    branch:
      - master
    event:
      - push

services:
- name: database
  image: mariadb
  ports:
    - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: rabbitmq
  image: rabbitmq:3.7.6
  ports:
    - 5672

- name: vault
  image: vault:0.11.4
  ports:
    - 8200
  environment:
    SKIP_SETCAP: 1
    VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    VAULT_ADDR: http://vault:8200
