kind: pipeline
name: default

steps:
- name: Configure Vault
  image: vault:0.11.4
  commands:
    - vault secrets disable secret
    - vault secrets enable -path=secret -version=1 kv
    - vault secrets enable totp
  environment:
    VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    VAULT_ADDR: http://vault:8200

- name: Run rspec
  image: ruby:2.6.5
  environment:
    DATABASE_HOST: database
    BARONG_EVENT_API_RABBITMQ_HOST: rabbitmq
    BARONG_VAULT_ADDRESS: http://vault:8200
    RAILS_ENV: test
    RAILS_MASTER_KEY:
      from_secret: rails_master_key
  commands:
    - bundle
    - ./bin/init_config
    - rake db:create db:migrate
    - rspec

- name: Bump and tag
  image: quay.io/openware/sdk-citools:2.3.1
  environment:
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    BRANCH_NAME: ${DRONE_BRANCH}
    REPO_NAME: ${DRONE_REPO}
    GITHUB_API_KEY:
      from_secret: kite_bot_key
    RAILS_MASTER_KEY:
      from_secret: rails_master_key
  commands:
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
  when:
    branch:
      - master
      - 2-2-stable
      - 2-3-stable

- name: Docker build and push
  image: plugins/docker
  environment:
    MAXMIND_LICENSE_KEY:
      from_secret: maxmind_license_key
  settings:
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    repo: quay.io/openware/barong
    registry: quay.io
    build_args_from_env:
      - MAXMIND_LICENSE_KEY
  when:
    branch:
      - master
      - 2-2-stable
      - 2-3-stable

- name: Redeploy on devkube
  image: rubykube/microkube:0.2.0
  environment:
    WEBHOOK_JWT_SECRET:
      from_secret: devkube_webhook_secret
  commands:
    - export latest_image=quay.io/openware/barong:$(cat .tags) 
    - cd /home/app
    - bundle exec rake payload:send[barong,$latest_image,http://www.devkube.com:1337]
  when:
    branch:
      - master

- name: Push and Notify
  image: quay.io/openware/sdk-citools:2.3.1
  environment:
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    BRANCH_NAME: ${DRONE_BRANCH}
    SDK_BRANCH: ${DRONE_BRANCH}
    REPO_NAME: ${DRONE_REPO}
    TELEGRAM_BOT_TOKEN:
      from_secret: telegram_bot_token
    TELEGRAM_CHAT_ID:
      from_secret: telegram_chat_id
    SLACK_TOKEN:
      from_secret: slack_token
    SLACK_CHANNEL:
      from_secret: slack_channel
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:postbuild[/drone/src]
  when:
    branch:
      - master
      - 2-2-stable
      - 2-3-stable

services:
- name: database
  image: mariadb
  ports:
    - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: rabbitmq
  image: rabbitmq:3.7.6
  ports:
    - 5672

- name: vault
  image: vault:0.11.4
  ports:
    - 8200
  environment:
    SKIP_SETCAP: 1
    BARONG_VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    BARONG_VAULT_ADDRESS: http://vault:8200

trigger:
  event:
    - push

image_pull_secrets:
- dockerconfigjson
