---
kind: pipeline
type: docker
name: MySQL 5.7 Test

services:
- name: database
  image: mysql:5.7
  ports:
    - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: rabbitmq
  image: rabbitmq:3.8.9
  ports:
    - 5672

- name: vault
  image: vault:1.12.3
  ports:
    - 8200
  environment:
    SKIP_SETCAP: 1
    VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    VAULT_ADDR: http://vault:8200

- name: redis
  image: redis:4.0
  ports:
    - 6379

steps:
- name: wait-for-services
  image: jwilder/dockerize
  commands:
  - dockerize -wait tcp://database:3306 -wait tcp://rabbitmq:5672 -timeout 1m -wait tcp://vault:8200 -timeout 1m

- name: Configure Vault
  image: vault:1.12.3
  commands:
    - vault secrets disable secret
    - vault secrets enable -path=secret -version=1 kv
    - vault secrets enable totp
  environment:
    VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    VAULT_ADDR: http://vault:8200

- name: Run rspec
  image: ruby:2.7.4
  environment:
    DATABASE_HOST: database
    BARONG_EVENT_API_RABBITMQ_HOST: rabbitmq
    BARONG_VAULT_ADDRESS: http://vault:8200
    BARONG_VAULT_TOKEN: changeme
    RAILS_ENV: test
    REDIS_URL: redis://redis:6379
    BARONG_REDIS_URL: redis://redis:6379
    RAILS_MASTER_KEY:
      from_secret: rails_master_key
  commands:
    - gem update bundler
    - bundle install --system
    - ./bin/init_config
    - bundle exec rake db:create db:migrate
    - bundle exec rspec

- name: Bump and tag
  image: quay.io/openware/sdk-citools:2.6.7
  environment:
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    BRANCH_NAME: ${DRONE_BRANCH}
    REPO_NAME: ${DRONE_REPO}
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
  when:
    branch:
      - "*-stable"

- name: Tag snapshot
  image: quay.io/openware/sdk-citools:2.6.7
  environment:
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    BRANCH_NAME: master
    REPO_NAME: ${DRONE_REPO}
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
  when:
    branch:
      - master
      - "fix/*"
      - "integration/*"

- name: Generate docs
  image:  timbru31/ruby-node:2.7-14
  environment:
    DATABASE_HOST: database
    BARONG_EVENT_API_RABBITMQ_HOST: rabbitmq
    BARONG_VAULT_ADDRESS: http://vault:8200
    RAILS_MASTER_KEY:
      from_secret: rails_master_key
  commands:
    - apt-get update
    - apt-get install -y git
    - gem update bundler
    - bundle install
    - bundle exec bin/gendocs
  when:
    branch:
      - master
      - "*-stable"

- name: Docker build and push
  image: plugins/docker
  environment:
    MAXMIND_LICENSE_KEY:
      from_secret: maxmind_license_key
  settings:
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    repo: quay.io/openware/barong
    registry: quay.io
    build_args_from_env:
      - MAXMIND_LICENSE_KEY
  when:
    branch:
      - master
      - "*-stable"
      - "fix/*"
      - "integration/*"

- name: Push and Notify
  image: quay.io/openware/sdk-citools:2.6.7
  environment:
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    BRANCH_NAME: ${DRONE_BRANCH}
    SDK_BRANCH: ${DRONE_BRANCH}
    REPO_NAME: ${DRONE_REPO}
    TELEGRAM_BOT_TOKEN:
      from_secret: telegram_bot_token
    TELEGRAM_CHAT_ID:
      from_secret: telegram_chat_id
    SLACK_TOKEN:
      from_secret: slack_token
    SLACK_CHANNEL:
      from_secret: slack_channel
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:postbuild[/drone/src]
  when:
    branch:
      - master
      - "*-stable"

- name: "Update global OpenDAX version"
  image: quay.io/openware/goci:0.0.11
  environment:
    GIT_TOKEN:
      from_secret: kite_bot_key
  commands:
    - /app/goci versions
  when:
    branch:
      - "*-stable"

trigger:
  event:
    - push

image_pull_secrets:
- dockerconfigjson

---
kind: pipeline
type: docker
name: MySQL 8.0 Test

services:
- name: database
  image: mysql:8.0
  commands:
    - /entrypoint.sh --default-authentication-plugin=mysql_native_password
  ports:
    - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: rabbitmq
  image: rabbitmq:3.8.9
  ports:
    - 5672

- name: vault
  image: vault:0.11.4
  ports:
    - 8200
  environment:
    SKIP_SETCAP: 1
    BARONG_VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    BARONG_VAULT_ADDRESS: http://vault:8200

- name: redis
  image: redis:4.0
  ports:
    - 6379

steps:
- name: Configure Vault
  image: vault:0.11.4
  commands:
    - vault secrets disable secret
    - vault secrets enable -path=secret -version=1 kv
    - vault secrets enable totp
  environment:
    VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    VAULT_ADDR: http://vault:8200

- name: Run rspec
  image: ruby:2.7.4
  environment:
    DATABASE_HOST: database
    BARONG_EVENT_API_RABBITMQ_HOST: rabbitmq
    BARONG_VAULT_ADDRESS: http://vault:8200
    BARONG_VAULT_TOKEN: changeme
    RAILS_ENV: test
    REDIS_URL: redis://redis:6379
    BARONG_REDIS_URL: redis://redis:6379
    RAILS_MASTER_KEY:
      from_secret: rails_master_key
  commands:
    - gem update bundler
    - bundle install --system
    - ./bin/init_config
    - bundle exec rake db:create db:migrate
    - bundle exec rspec

trigger:
  event:
    - push
  branch:
    - "compatibility/*"
    - "*-stable"
