version: '3'

services:
  vault:
    image: vault:1.6.7
    volumes:
      - vault_data:/vault
      - ./config/vault:/tmp/policies
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200
volumes:
  vault_data:
