{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "barong.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "barong.fullname" . }}
  labels:
{{ include "barong.labels.standard" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ $servicePort }}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range $host := .Values.ingress.hosts }}
  - secretName: {{ $host | include "barong.utils.tls" }}
    hosts:
    - {{ $host }}
  {{- end -}}
  {{- end -}}
{{- end -}}
