apiVersion: v1
kind: Secret
metadata:
  name: {{ template "barong.fullname" . }}
  labels:
{{ include "barong.labels.standard" . | indent 4 }}
type: Opaque
data:
  dbPassword: {{ default "" .Values.db.password | b64enc }}
  {{- if .Values.secretKeyBase }}
  secretKeyBase: {{ .Values.secretKeyBase | b64enc }}
  {{- else }}
  secretKeyBase: {{ randAlphaNum 128 | b64enc }}
  {{- end }}
  {{- if .Values.deviseSecretKey }}
  deviseSecretKey: {{ .Values.deviseSecretKey | b64enc }}
  {{- else }}
  deviseSecretKey: {{ randAlphaNum 128 | b64enc }}
  {{- end }}
  twilioAccountSid: {{ required "twilio.accountSid is required!" .Values.twilio.accountSid | b64enc }}
  twilioAuthToken: {{ required "twilio.authToken is required!" .Values.twilio.authToken | b64enc }}
  twilioPhoneNumber: {{ required "twilio.phoneNumber is required!" .Values.twilio.phoneNumber | b64enc }}

  storageAccessKey: {{ required "storage.accessKey is required!" .Values.storage.accessKey }}
  storageSecretKey: {{ required "storage.secretKey is required!" .Values.storage.secretKey }}

  {{- if .Values.vault.enabled }}
  vaultToken: {{ .Values.vault.token | b64enc }}
  {{- end }}
  {{- if .Values.jwtSharedSecretKey }}
  jwtSharedSecretKey: {{ required "jwtSharedSecretKey" .Values.jwtSharedSecretKey | b64enc  }}
  {{- end }}
