apiVersion: v1
kind: Secret
metadata:
  name: {{ template "barong.fullname" . }}
  labels:
{{ include "barong.labels.standard" . | indent 4 }}
type: Opaque
data:
  dbPassword: {{ default "" .Values.db.password | b64enc }}
  {{- if .Values.secretKeyBase }}
  secretKeyBase: {{ .Values.secretKeyBase }}
  {{- else }}
  secretKeyBase: {{ randAlphaNum 128 | b64enc }}
  {{- end }}
  {{- if .Values.deviseSecretKey }}
  deviseSecretKey: {{ .Values.deviseSecretKey }}
  {{- else }}
  deviseSecretKey: {{ randAlphaNum 128 | b64enc }}
  {{- end }}
  twilioAccountSid: {{ required "twilioAccountSid is required!" .Values.twilioAccountSid }}
  twilioAuthToken: {{ required "twilioAuthToken is required!" .Values.twilioAuthToken }}
  twilioPhoneNumber: {{ required "twilioPhoneNumber is required!" .Values.twilioPhoneNumber }}