apiVersion: v1
kind: Secret
metadata:
  name: {{ template "barong.fullname" . }}
  labels:
{{ include "barong.labels.standard" . | indent 4 }}
type: Opaque
data:
  dbPassword: {{ default "" .Values.db.password | b64enc }}
  {{- if .Values.secretKeyBase }}
  secretKeyBase: {{ .Values.secretKeyBase | b64enc }}
  {{- else }}
  secretKeyBase: {{ randAlphaNum 128 | b64enc }}
  {{- end }}
  {{- if .Values.deviseSecretKey }}
  deviseSecretKey: {{ .Values.deviseSecretKey | b64enc }}
  {{- else }}
  deviseSecretKey: {{ randAlphaNum 128 | b64enc }}
  {{- end }}
  twilioAccountSid: {{ required "twilio.accountSid is required!" .Values.twilio.accountSid | b64enc }}
  twilioAuthToken: {{ required "twilio.authToken is required!" .Values.twilio.authToken | b64enc }}
  twilioPhoneNumber: {{ required "twilio.phoneNumber is required!" .Values.twilio.phoneNumber | b64enc }}
  gcsAccessKeyId: {{ required "gcs.accessKeyId" .Values.gcs.accessKeyId | b64enc }}
  gcsSecretAccessKey: {{ required "gcs.secretAccessKey" .Values.gcs.secretAccessKey | b64enc }}