apiVersion: v1
kind: Service
metadata:
  name: {{ template "barong.fullname" . }}
  labels:
{{ include "barong.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "barong.name" . }}
    release: {{ .Release.Name }}
