# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  vault_adress: <%= ENV["VAULT_ADDR"] %>
  vault_token: <%= ENV["VAULT_TOKEN"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62363a59925a0331f946bf3271c6652384c8c211b05a82075e402cc2a514b62414df188585313ecd911b1f3cd0c9847fa2e1bf8ff0fb35a042d0d9c8a21988c9
  devise_secret_key: 92e7de6877d36ea42ce364e1c2b93171c0d10869d31b998c0cbc61285784697c0077686203ff85f53496809975f4731fa4a6458ad39523f0be114a7812777a10

  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_phone_number: '+15005550006'

  storage_provider: <%= ENV.fetch('STORAGE_PROVIDER', 'local') %>
  storage_bucket_name: <%= ENV['STORAGE_BUCKET_NAME'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  storage_secret_key: <%= ENV['STORAGE_SECRET_KEY'] %>
  storage_region: <%= ENV['STORAGE_REGION'] %>

  jwt_shared_secret_key: <%= ENV.fetch('JWT_SHARED_SECRET_KEY', 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBOWt6akVBb2NJSWZva3hhSTZHMXMwRzczWnlyWXVOcWtnaVR2ek9haGRoSE9FUWFJCmpEY3EvRzVuSW5Ic25qdkZMM3oyY2tkTFBURWh3VE5HNlEybkZ2TkRTQlJHSVRJSFVGaW1KM2NBTTlzYzl2NzYKaE9vUDh5NUd4RHllMjcwWjE4UWFjOEdkMGZyZGZ6Z1lvQ3BTWk1yK3c5ZFRIU0dpcXczaW9YUjJ5akNSZm5XTgp1NXM4dGJaL0s4aFpUYUx5cUs1Znd6UTJrR3F4dVl1YnRuRlpOYUhmN2ZNL09IOXZETG1MNi9yczhPWURiaUhQCjFvVkFJUVliZEZpNU4zZlJhcnJQdGRrMGlsZ2VNb0Z3YmlidDg1Z2xHYUJldE5JVnN0QkVzdXRvaW5CUWlmYzgKNUpGdmpXYVZNcmdrc2RaVnVNWVoxS0dYN2k4KzNDNzRNYzRXdHdJREFRQUJBb0lCQUZZMGp2eWNMVUFOa1k5NQp3YTFvTHorOHR3YjY3aU8xRXdNaUhuUmUvSUF3dHlrcVdqeUpTcGhUby9GZ1ltcjNqSXFVZUVXRFFvaEdYQVFkCkNHS2xqcWZ2dU1yUG5jUWNtSWE4b0ZzTHdaeGt3bnlJdmZJcllpM0JNcStZY0JtRTFEaTZ3RzluZ3U5dG1IemcKaTIzem9pYjVEYlpKOVNNckZKNCtHK1phdHdFSTB2VHBWbENVeDQ5UHRIdzJkWWJhR04xMS8rZnQ1MEJYdytYQgp0ZVpFTjVOYTR0SEhWcHB3aUdFd1BtblhyN292Vmo0eVFzdnhHaEVOTUlrMkNJVkxpQmlhUWhoNTFZYUdnc1AyCmRpeVZRdXF1L2Uyd3cyYzh1c2tlKzN4aW5QdThiY3pJQVZoY3l2RFJlMzFmN0VBOWdYRHU5SDFzQUxrajdXNjYKdjkrRjJhRUNnWUVBLy9Vd3Q1L1lBT3Q1alhIbkRjZ3drbzNSTDlwZUpSUzF3K1BSbEhWV3NmdExZTWx3SERORApwbVRNYmtJUE9yelpqMmJlODcwZm02N3pscGczVXdJbHlmTkhwb0xQL0hRVUp5eS82TWtNbDNhUTQ4MktHM3ovCmdKMDZwQkdGMzZ0Uk1iQ25zN09vOEhZRzNMK0FWRVZ0cnpWc3VnNHBRc21lZ1lCVmNtcnBsRGtDZ1lFQTlsZEoKN3lkUURpL2xjckt1b1JBdEhjdEhwS3Z5VUVVQ1JNMlB3WkY3R3ExVXFoUzFDdGxubDBNNnBDdGIrY25QbWU5SQpZbUZjZCtRZWE3TVpHVXduZmZldUpjeGg0TlI4SjZlZFRTRThpZ3owbG4wdmZ0WnBmcUdLUEtsZE4wakdDdHVvCkZRR0U0cXQ0SXVPNC9Yemlhazd2VlZNbmNJU2JCZlk0VURRUlltOENnWUJ5a0xiTG1mbysveWNiRG42VEJxWG4KRXg4c3doc2RrZFdCNXJqcU1GTXJ1d1VVUDFXMDZhVkFGeUlCd0FPOUVNWjRqMXovMEFrVDBBMHJ2Tm9XaDRHTwprUnZqQmU0K1cxNmg0ai9MM0NHTXNmOU1WN1dYZEMyUXpjOXZuSUJGaXhMK29NbVBmNzBBVkhQaDNyMTcrcytMCmV1ZzlweFVFMWVYaXBTU1o0QXpJMFFLQmdHTEJVWmwzZUNlSDJnTW1VTTJ1NzNkUFJCUm0va2hoc2V3bFFHbEkKU2tMQ2svdHZPN2p5dVEyeDNQTnRrbnpNQTliaFQzSnBONm0wb09GcU5qaW5CL24rN2lpbkMrSVhMUUswdG1IeQpYaE8xNStQZ29jYkdiQnBnNWtzMVZuSlFVVnlPL0k0WFFzK2dFQlJrbUllK3BnSWFUT1kyNU11OXpXd1JiamZ3Cjk3c3ZBb0dBSTYvOEtRdE1ZMWkyenNjUVczL0h2eUxBM0s4N1dUMjdTU3RwUTRCeWhQTmJtYmZvbUpmbXQrZmkKN2NyTXlEdFlUNTVOeW5UOW5QTUJZTXMyT2J5WWdwNjIvZ3daOG03V3luQitRMm1ENUtaYmc5eGwvNzVUeDlzVgpVbVNPRFdib0lUOFlwTDh6WS9mN29VVk0zRnVvZUJqQ1hybkE4S1c4Q082Q2dicjRETGM9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==') %>
  jwt_public_key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzak1ZYnpOcndpSnFmZE9yNGZRZApPVEFUcUErNitIL2Vqb0ZaeHJwdFVQblBweGUxSlh6SVY0czVSKzgvcVF3d1JJalBWZFk0RVowSzNBZnU5RExoCjIySUF6d2xvSWxKd3N1bHA1bVFYT3dHZUhLSGdZNktzb1Z3cnpIRnliRk9ibkJvYkpzYkFmcDJYL2Y4SHNVbG0KWjllQ2w1V3B1U25KWWhjSUVHTWdlSmwxeHd4SmlHckJKQ0pGUmdiT3FWWlhSZ29VLzZVbFNOaVRuVk01UHREMwoxeW5yckUyeTkyOXhQV3JsSm1USTJlTXdMd3ZnMXUzVDEzYnRCekJhbnFuRkRVUmdRczNrZnA4NVlwaEhGbGU0CmE1Sk91aWdycWlZTkV4dEJ0ZzBXQ3RsWDVlTWI0VEdTTWR2ZmtqUDgySVJtZHdRcy9CSkRwUy9ubE0vejdvNzUKV1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

test:
  secret_key_base: f35908345f0ee30027ecd785cf207a2311a70ee31d5a9e2153c4fd07dae216fae9cad4d47b5c87b764f28d6519e320ddae948038ca184ced5a457b03b94e859d
  devise_secret_key: d419eb32eb538bfcdbdeee9f71d1b70889950c870652965e26d324e78a5c983d814e7873b55693e0e90701db6e3d3fad956e63b823ce993685156141afbe4c66

  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_phone_number: '+15005550006'

  storage_provider: <%= ENV.fetch('STORAGE_PROVIDER', 'local') %>
  storage_bucket_name: <%= ENV['STORAGE_BUCKET_NAME'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  storage_secret_key: <%= ENV['STORAGE_SECRET_KEY'] %>
  storage_region: <%= ENV['STORAGE_REGION'] %>

  jwt_shared_secret_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBc2pNWWJ6TnJ3aUpxZmRPcjRmUWRPVEFUcUErNitIL2Vqb0ZaeHJwdFVQblBweGUxCkpYeklWNHM1Uis4L3FRd3dSSWpQVmRZNEVaMEszQWZ1OURMaDIySUF6d2xvSWxKd3N1bHA1bVFYT3dHZUhLSGcKWTZLc29Wd3J6SEZ5YkZPYm5Cb2JKc2JBZnAyWC9mOEhzVWxtWjllQ2w1V3B1U25KWWhjSUVHTWdlSmwxeHd4SgppR3JCSkNKRlJnYk9xVlpYUmdvVS82VWxTTmlUblZNNVB0RDMxeW5yckUyeTkyOXhQV3JsSm1USTJlTXdMd3ZnCjF1M1QxM2J0QnpCYW5xbkZEVVJnUXMza2ZwODVZcGhIRmxlNGE1Sk91aWdycWlZTkV4dEJ0ZzBXQ3RsWDVlTWIKNFRHU01kdmZralA4MklSbWR3UXMvQkpEcFMvbmxNL3o3bzc1V1FJREFRQUJBb0lCQVFDTlJrN24waGRyT0llKwpxN0tJRjFXWHdoTERXWDA4aDN0MDlQMnN2SjN2NWEwSDVwYTVXcDBtTW4wK0YySWI3a3JSK3JpTmI2RFI3ZlB2CkR1Y1ZlTVZ3Zk5qeFNwN2hId1MwQXJMdmNZaXRRaElNMXhValNKT2Q5WW5Qc2wwcG5uc3VuYy9LeFNWVS9ESEUKcjR4MHRDRlkwQlY3Z2E2bDJvZ0ttUUhPcEJmWkkxWC9sNGQ4RUpsUkhrNVNWSWJJUHVDTDZWaVE0bE9icmgwdwp1T2ErV1FjTWNEYlhoNWI2OEZQYWhFM2JGUTZxYVNoVUZ0alVxWTMvTkFnejZxc3BST3lFUXNYcmN2WDlZRnZyCjk1WDE4R09aSVZtY0JFQVU3NXhqc0xtM1lOTkxFbndnckYrazJESjd2TU1kV1FPaGtSUEJ6VGtEenVIWkcwUm0Kd3BtS3lSWDFBb0dCQU5ZRlVETjMwQVZMUmlnSU9ldGFYa0MrdGpqakVwVXk0OXlWcXJRVDJYUnlodWp1ZjZRZwpVR2grVXVWMUJwUnhycDhkN1FBMWxkT0E2cHdGOHRwTUIxbUZrRmpsWVV1bXRzQVFXcVUwdHNrQTYzTlpOTzFpCm5kNUtrczd4RXVnM2EveFZZWC9PODNvcEJWVVZYYzVWWUFGOHo4UXR4by9ZdjQzSFVSSmQ4a2FiQW9HQkFOVW4KRldlOEFUeUJtMVJ5YnRQN01jVnNmL0RRZW1YTkNSTVlOQVUwSE41MFZWZTNZZmsxSC9UaGhoNXBad2FLOWx1VQoyTjR5MnZ5RUM1ZTBiVFNmVWZtNkRXZ0tHMDZHaDVDeThFTDdXZ0dZWVlTMzJkendEVW5EVDBXSzZIbzFBL004CmQyRWJZaG1TZGtlcVFtbGVnVnU4RUVlTlpwVG1oY3ZTWU9EUnFZVWJBb0dBRXhXZU5UaTE0QUw2V28rQk9xOXcKUUMzQmFnazFtd0JTdVZUUFNBZU5HSWt0NW85OTZsREhXc29JOGxVaEpST09FcnBFYkFSYk8rVC9Cckt4R1M0MgphWkV6Y2ZuaVZ6Q2lrelhpSDJFMysyeU5rbGVlRkp6Nm50dmZnM3lUeHdsS0k5SXBRNUJjdmNQeXFjZWgrY2c3CksyYkowQ0NVMkRibnZlak1IZXNxczRrQ2dZRUFueTNXMEdjWVRVVkU2S1drbW0zbTExYVZuUk16dEw2UDNsQ2UKMkp2NFN6QjVZMDR4dmxlc0M4WTMwSkpLUEJxZXEvbldrdWxMbkhSSDYveno2TzVwMjZMVHpEUnYvQTUvUXRJKwpsdWI2YW1LUHdQdERtYmt6VXppbUJIc2Q3ZFdWbzVvdVZMaU1aQ2g2YUQ1LzVneUxjaVJaeS9XTysvZkRSMWxPCnU5WVhVSzBDZ1lFQXV0MXZXVE9QbUZRbEV2cjBUNGZsQk9RQlpMTU5YbGtJMnI5WSt5MEZoVnF5Q0dsSzNXM0MKbVdPOGgxNXpNTmVCQnVkdU5sdzR0MmdHUXJvWVRyVHVyblo0ekZqU2NXamNreDlOMXI4WGZvWkhwaWhOSUZHYQpLUWxQUnNJQjQrblFPWlBCWXNsZzZWc1BiUnpaL3pNdE5VRzJKWTAweVFYMmhvYzNtK0tFYU9BPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  jwt_public_key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzak1ZYnpOcndpSnFmZE9yNGZRZApPVEFUcUErNitIL2Vqb0ZaeHJwdFVQblBweGUxSlh6SVY0czVSKzgvcVF3d1JJalBWZFk0RVowSzNBZnU5RExoCjIySUF6d2xvSWxKd3N1bHA1bVFYT3dHZUhLSGdZNktzb1Z3cnpIRnliRk9ibkJvYkpzYkFmcDJYL2Y4SHNVbG0KWjllQ2w1V3B1U25KWWhjSUVHTWdlSmwxeHd4SmlHckJKQ0pGUmdiT3FWWlhSZ29VLzZVbFNOaVRuVk01UHREMwoxeW5yckUyeTkyOXhQV3JsSm1USTJlTXdMd3ZnMXUzVDEzYnRCekJhbnFuRkRVUmdRczNrZnA4NVlwaEhGbGU0CmE1Sk91aWdycWlZTkV4dEJ0ZzBXQ3RsWDVlTWI0VEdTTWR2ZmtqUDgySVJtZHdRcy9CSkRwUy9ubE0vejdvNzUKV1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>

  storage_provider: <%= ENV.fetch('STORAGE_PROVIDER', 'local') %>
  storage_bucket_name: <%= ENV['STORAGE_BUCKET_NAME'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  storage_secret_key: <%= ENV['STORAGE_SECRET_KEY'] %>
  storage_region: <%= ENV['STORAGE_REGION'] %>

  jwt_shared_secret_key: <%= ENV["JWT_SHARED_SECRET_KEY"] %>
  jwt_public_key: <%= ENV["JWT_PUBLIC_KEY"] %>
