local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
# Mount file with any production-ready setup
# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# Use rails credentials:edit to set the Aliyun Storage secret (as oss-access-key-id)
# alibaba:
#   service: Aliyun
#   access_key_id:  <%= Rails.application.credentials.dig(:aliyun_storage, :storage_access_id) %>
#   access_key_secret:  <%= Rails.application.credentials.dig(:aliyun_storage, :storage_access_secret) %>
#   bucket: your_bucket_name
#   endpoint: https://oss-cn-beijing.aliyuncs.com
#   # path prefix, default: /
#   path: "my-app-files"
#   # Bucket mode: [public, private], default: public
#   mode: "public"

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
