apiVersion: v1
appVersion: 0.9.0
description: A Helm chart for Vault, a tool for managing secrets
home: https://www.vaultproject.io/
icon: https://www.vaultproject.io/assets/images/mega-nav/logo-vault-0f83e3d2.svg
maintainers:
- email: jpds@protonmail.com
  name: jpds
name: vault
sources:
- https://github.com/hashicorp/vault
- https://github.com/hashicorp/docker-vault
version: 0.3.1
